name: reown_walletkit
description: "The communications protocol for web3"
version: 1.0.0
homepage: https://github.com/reown-com/reown_flutter
repository: https://github.com/reown-com/reown_flutter

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  event: ^2.1.2
  flutter:
    sdk: flutter
  reown_core:
    path: ../reown_core
  reown_sign:
    path: ../reown_sign

dev_dependencies:
  build_runner: ^2.4.7
  build_version: ^2.1.1
  dependency_validator: ^3.2.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  http: ^1.2.2
  # freezed: ^2.4.5
  # json_serializable: ^6.7.0
  mockito: ^5.4.3
  package_info_plus: ^7.0.0
  reown_appkit:
    path: ../reown_appkit

platforms:
  android:
  ios:
  web:
  macos:
  linux:
  windows:
