name: reown_appkit
description: "The communications protocol for web3"
version: 1.0.0
homepage: https://github.com/reown-com/reown_flutter
repository: https://github.com/reown-com/reown_flutter

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  appcheck: ^1.5.1
  cached_network_image: ^3.3.1
  coinbase_wallet_sdk: ^1.0.9
  collection: ^1.17.2
  convert: ^3.1.1
  cupertino_icons: ^1.0.2
  custom_sliding_segmented_control: ^1.8.1
  event: ^2.1.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  http: ^1.1.2
  json_annotation: ^4.8.1
  plugin_platform_interface: ^2.1.8
  qr_flutter_wc: ^0.0.3
  reown_core:
    path: ../reown_core
  reown_sign:
    path: ../reown_sign
  shimmer: ^3.0.0
  url_launcher: ^6.2.5
  uuid: ^4.3.3
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.16.0
  webview_flutter_wkwebview: ^3.13.0

dev_dependencies:
  build_runner: ^2.4.7
  build_version: ^2.1.1
  dependency_validator: ^3.2.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.0
  mockito: ^5.4.3
  package_info_plus: ^7.0.0
  reown_walletkit:
    path: ../reown_walletkit

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
    # This plugin project was generated without specifying any
    # platforms with the `--platform` argument. If you see the `some_platform` map below, remove it and
    # then add platforms following the instruction here:
    # https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms
    # -------------------
      some_platform:
        pluginClass: somePluginClass
    # -------------------

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
  assets:
    - lib/modal/assets/
    - lib/modal/assets/dark/
    - lib/modal/assets/light/
    - lib/modal/assets/icons/
    - lib/modal/assets/icons/regular/
    - lib/modal/assets/help/
    - lib/modal/assets/png/
    - lib/modal/assets/png/2.0x/
    - lib/modal/assets/png/3.0x/

# TODO check this
platforms:
  android:
  ios:
  # web:
  # macos:
  # linux:
  # windows:
